// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5vYqCqRIivkLgRJK2U_1wTxH_FPRo2Sc',
    appId: '1:497163909551:android:d965b14baac8566eab975a',
    messagingSenderId: '497163909551',
    projectId: 'app-app-4fb0a',
    databaseURL: 'https://app-app-4fb0a-default-rtdb.firebaseio.com',
    storageBucket: 'app-app-4fb0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYW-TlOGmvaIebakjhP1XD8qCy3kRTnw4',
    appId: '1:497163909551:ios:bafcca141cd9b4baab975a',
    messagingSenderId: '497163909551',
    projectId: 'app-app-4fb0a',
    databaseURL: 'https://app-app-4fb0a-default-rtdb.firebaseio.com',
    storageBucket: 'app-app-4fb0a.appspot.com',
    iosBundleId: 'com.example.rebookApp',
  );
}
